feat: add binding validation
weweb-assets/plugin-xano pull request #16
Opened 2023-08-30 17:11 UTC by AlexisJC

2023-09-05 15:10 UTC, Dams-d approved these changes

2023-09-05 15:12 UTC, Dams-d requested changes

2023-09-05 15:12 UTC, Dams-d commented on src/wwPlugin.js
> +            wwLib.wwNotification.open({
Log the error if possible

2023-09-05 15:40 UTC, MarcFabre approved these changes

2023-09-06 08:53 UTC, Dams-d approved these changes

2023-09-07 08:12 UTC, merged